### ISSUE TITLE
Premature ending of GoA Set Up

### ISSUE THREAD

**Issue by John-Weingardt** [Weingardt-Games/panjwayi#114]
A small bug, perhaps premature, but when I was placing the GoA pieces, I still hadn't placed AIR.  I did click on an ANA piece, and took a move.

The AIR piece then moved to the TB Reinforcement Box, and the TB player got to place it … in the GoA area!

A minor glitch, but for the files .. :)

**Comment by tylerecouture** [comment]
Good to have all this stuff documented, even if it is early!
