### ISSUE TITLE
TB player sets up

### ISSUE THREAD

**Issue by John-Weingardt** [Weingardt-Games/panjwayi#22]
- [x] TB player sets up second
- [x] One piece per square (always)
- [x] Must place in Rows 13-16 (TB set up area)
- [ ] 9* x POP/INS (choice of which side up)
- [ ] Number of POP/INS may vary
- [ ] IEDs remain in reinforcement box

**Comment by tylerecouture** [comment]
Can you split these into their own tasks, with details if needed?
-Number of POP/INS may vary (not enough info/context here for me unless I dig into rules)
-IEDs remain in reinforcement box (not enough info/context here for me unless I dig into rules)

The rest are complete and this can be closed

**Comment by John-Weingardt** [comment]
IED set-up appears solved (you have them started in the Reinforcement Box) - the remainder of IED questions should be answered by #26

**Comment by John-Weingardt** [comment]
Starting POP/INS is found in #17
