### ISSUE TITLE
Village Locations

### ISSUE THREAD

**Issue by John-Weingardt** [Weingardt-Games/panjwayi#4]
Sanjaray = M3
Howz-e-Medad = C4
Pashmul = F6
Salehan = O7
Bazaar-e-Panjwayi (North) = I8
Bazaar-e-Panjwayi (South) = H9
Nalgham = B10
Salavat = K11
Nakhonay = N13
Zangabad = D14

**Comment by John-Weingardt** [comment]
With new notation, I would label these:

Sanjaray = 13 03
Howz-e-Medad = 03 04
Pashmul = 06 06
Salehan = 15 07
Bazaar-e-Panjwayi (North) = 09 08
Bazaar-e-Panjwayi (South) = 08 09
Nalgham = 02 10
Salavat = 11 11
Nakhonay = 14 13
Zangabad = 04 14

**Comment by John-Weingardt** [comment]
Should I split this into 10, or keep as one?

Not quite how granular is useful, and how much is too much?

**Comment by tylerecouture** [comment]
This one is fine.  Do you want the position labels displayed in the game somewhere?  Like as players move their mouse around the grid, the coordinates would appear in a UI widget somewhere?
