### ISSUE TITLE
MOVE INF

### ISSUE THREAD

**Issue by John-Weingardt** [Weingardt-Games/panjwayi#42]
May move one square, like king in chess, horizontal, vertical, diagonal.
May enter, and destroy, square with INS
May not enter square with POP, IED, AIR, LAV, INF, ANA, ANP
If it did not attack INS after moving first square, it **may** move a second square (GoA player choice)
Second move exactly the same:
May move one square, like king in chess, horizontal, vertical, diagonal.
May enter, and destroy, square with INS
May not enter square with POP, IED, AIR, LAV, INF, ANA, ANP

**Comment by John-Weingardt** [comment]
Further to Issue #25  , all INF should 'glow' on GoA turn. You already have a mount/dismount icon developed. (issue #28 
For potential movement, all squares should glow - green to move - red(?) to attack - if green/red square selected, the unit moves. Destroyed units move to reinforcement box.
Confirm/cancel afterwards (#29

NOTE THAT since INF can only attack once in a turn, all the squares can be highlighted - INF doesn't have to click twice to move two squares.

**Comment by tylerecouture** [comment]
What am I reviewing? Is this task going to be split?  Every line could be its own issue.

**Comment by John-Weingardt** [comment]
Will do
    On Wednesday, May 13, 2020, 03:02:41 p.m. EDT, tylerecouture <notifications@github.com> wrote:  
 
 


What am I reviewing? Is this task going to be split? Every line could be its own issue.

**Comment by John-Weingardt** [comment]
Split to tasks #120 #121 and #122
