### ISSUE TITLE
Select Fonts

### ISSUE THREAD

**Issue by tylerecouture** [Weingardt-Games/panjwayi#71]
We need 
- [ ] display font (for titles) and 
- [ ]  text font (for content)

Find one you can license or pick Open License fonts from somewhere like Google Fonts:
https://fonts.google.com/

**Comment by John-Weingardt** [comment]
Tylere,

Matura (the text I used for the board game) requires a payment to download the font.

However, I found a good alternative, "ALADIN":

https://fonts.google.com/specimen/Aladin?preview.text=Panjwayi&preview.text_type=custom&sort=alpha

I would use ALADIN for the buttons if it is not too confusing.
For the stylized title, we can use an image of "Panjwayi" in the original Matura font.

I've used ARIAL ROUNDED MT BOLD for the words "Counterinsurgency in Afghanistan" and ARIAL for text on the box, in the rules, etc.

Thoughts?
