### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by tylerecouture** [Weingardt-Games/panjwayi#72]
Game needs an Icon!

**Comment by John-Weingardt** [comment]
How about this for an Icon?
![Panjwayi Icon 01](https://user-images.githubusercontent.com/64376950/80851627-da5a8a00-8bf0-11ea-91ef-cfb9114c2542.jpg)
![Panjwayi Icon 02](https://user-images.githubusercontent.com/64376950/80851628-db8bb700-8bf0-11ea-9a50-7acc22a3496d.jpg)

**Comment by John-Weingardt** [comment]
Perhaps a square version with the title on it?  A combination of the two provided above?

**Comment by John-Weingardt** [comment]
![Panjwayi ICON](https://user-images.githubusercontent.com/64376950/80852304-74243600-8bf5-11ea-9544-073c8c917e7f.PNG)
I think we have a winner - 864 by 864 px

Close it if you are happy.

**Comment by tylerecouture** [comment]
That's an awesome banner and hi-res icon.  How about little icon (think the icons on your phone, or the symbol that appears in browser tabs.  These are usually 64x64 or 128 x 128 pixels.

**Comment by John-Weingardt** [comment]
Resized
![Panjwayi ICON - 64 x 64](https://user-images.githubusercontent.com/64376950/80892514-c36f7280-8c98-11ea-800c-187a1307e921.PNG)
![Panjwayi ICON - 128 x 128](https://user-images.githubusercontent.com/64376950/80892515-c5393600-8c98-11ea-8c99-4653706b302b.PNG)

**Comment by John-Weingardt** [comment]
Also, here is an alternate - maybe more 'iconic.'
![ICON 3 64 x 64](https://user-images.githubusercontent.com/64376950/80892777-be132780-8c9a-11ea-81c9-024a0aaec434.PNG)
![ICON 3 128 x 128](https://user-images.githubusercontent.com/64376950/80892778-beabbe00-8c9a-11ea-9da7-840bd89ae94b.PNG)
![ICON 3 864 x 864](https://user-images.githubusercontent.com/64376950/80892779-beabbe00-8c9a-11ea-8f23-70fe3097a9a0.PNG)

**Comment by John-Weingardt** [comment]
I centred the 'P' - it was bugging me.  Here's an 864, 128, and 64 sq pixel version.  I think we're good?

![ICON 4 64 x 64](https://user-images.githubusercontent.com/64376950/81962670-0a872d00-95e2-11ea-8a03-221b3c0d966c.PNG)
![ICON 4 128 x 128](https://user-images.githubusercontent.com/64376950/81962673-0b1fc380-95e2-11ea-9f37-97394ccce3d1.PNG)
![ICON 4 864 x 864](https://user-images.githubusercontent.com/64376950/81962676-0b1fc380-95e2-11ea-9bee-c07e5197172f.PNG)
