### ISSUE TITLE
pick a license for your code

### ISSUE THREAD

**Issue by tylerecouture** [Weingardt-Games/panjwayi#74]
Open Source? (I recommend this if you're already sharing it, and I'm working on it for free =D
https://choosealicense.com/licenses/

Let me know if you have any questions.

Proprietary? You'll have to figure it out

**Comment by John-Weingardt** [comment]
Gosh, I'm good with anything, so long as they source is acknowledged, and changes are identified.  

What do you recommend, in that case?

**Comment by tylerecouture** [comment]
MIT is probably the most common.
