### ISSUE TITLE
UI assets

### ISSUE THREAD

**Issue by tylerecouture** [Weingardt-Games/panjwayi#76]
You'll need to choose assets for the game's GUI.  We can find a pre-made set online (free or paid) or build our own.

For now I'm going to use this free set:
https://craftpix.net/freebies/free-tds-modern-gui-pixel-art/

You can search for other pre-made GUI assets on the two pages here:
https://craftpix.net/categorys/gui/page/2/
https://craftpix.net/categorys/gui/

or anywhere else on the internet!

**Comment by tylerecouture** [comment]
Tons more here:
https://www.gamedevmarket.net/category/gui/

**Comment by John-Weingardt** [comment]
Here are some I like … let me know if you want some … I'm sort of rich!  Some are not on point (FPS, RPG, fantasy, too cartoonish) but even if we could adapt some of the look and feel to our purposes?

https://www.gamedevmarket.net/asset/black-style-gui/

https://assetstore.unity.com/packages/tools/gui/military-ui-141928

https://graphicriver.net/item/war-game-army-mobile-ui/25157896

https://graphicriver.net/item/fantasy-gui/19938318

https://graphicriver.net/item/retro-ui-pack/10130676

I like these two a lot - a serious tone:
https://graphicriver.net/item/game-ui-interface-pack-gothic-dark-fantasy-edition/17017397

https://graphicriver.net/item/rpg-user-interface-elements/4444118

https://graphicriver.net/item/rpg-user-interface-set/9712587

**Comment by John-Weingardt** [comment]
https://www.gamedevmarket.net/asset/mobile-fps-game-gui-buttons-and-icons/

I really like this - it's generic, but the colours are good:
https://www.gamedevmarket.net/asset/casual-ui/

https://www.gamedevmarket.net/asset/military-ui/

Some free buttons
https://www.gamedevmarket.net/asset/play-button/

3 simple and related GUI:
https://www.gamedevmarket.net/asset/vector-game-user-interface-9586/
https://www.gamedevmarket.net/asset/game-user-interface-vector-9590/
https://www.gamedevmarket.net/asset/vector-game-user-interface-9584/

**Comment by John-Weingardt** [comment]
Cool crosshairs:
https://www.gamedevmarket.net/asset/crosshairs-sprite-game-pack-3215/

https://www.gamedevmarket.net/asset/gui-icons-pack-1-1818/

**Comment by John-Weingardt** [comment]
Can we close this one?

**Comment by tylerecouture** [comment]
Yep, if you're happy with the widgets and things I'm using.  We can always tweak and fine tune later.
