### ISSUE TITLE
Indicate village control

### ISSUE THREAD

**Issue by tylerecouture** [Weingardt-Games/panjwayi#86]
How do you want to do this?  I think easiest might be just to use your existing red and white outlines.   When Taliban take a village over turn it white, and when GoA does turn it red? Whe could also add a hover that shows the flag of the controller?

Any other ideas?

**Comment by John-Weingardt** [comment]
Yes, I think that works perfectly … there will be a requirement for a third colour (neutral) as some Action Cards create neutral control.  For neutral? - blue?  pink?  Candy Cane?  (I'm serious!)

Black is hard to see and green looks 'GoA'-ish.
